import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, ChevronUp, Brain } from "lucide-react";
import { useState } from "react";

export default function AIExplanation({ result, isVisible }) {
  const [expanded, setExpanded] = useState(true);

  if (!result || !isVisible) return null;

  const steps = (result.explanation || "")
    .split(/\.\s+/)
    .filter(Boolean)
    .map((s) => s.trim() + (s.endsWith(".") ? "" : "."));

  return (
    <motion.section
      id="ai-explanation"
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, delay: 0.2 }}
      className="py-8 px-4 sm:px-6"
    >
      <div className="max-w-4xl mx-auto">
        <div className="glass-card overflow-hidden">
          {/* Header */}
          <button
            onClick={() => setExpanded(!expanded)}
            className="w-full flex items-center justify-between p-6 text-left hover:bg-blue-50/30 dark:hover:bg-blue-900/10 transition-colors"
            id="ai-explanation-toggle"
          >
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-500 to-blue-500 flex items-center justify-center flex-shrink-0">
                <Brain className="w-5 h-5 text-white" />
              </div>
              <div>
                <span className="section-label block">AI Reasoning</span>
                <h3 className="font-semibold text-gray-800 dark:text-gray-100">
                  How I reached this conclusion
                </h3>
              </div>
            </div>
            {expanded ? (
              <ChevronUp className="w-5 h-5 text-gray-400" />
            ) : (
              <ChevronDown className="w-5 h-5 text-gray-400" />
            )}
          </button>

          {/* Expandable content */}
          <AnimatePresence>
            {expanded && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: "auto", opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                transition={{ duration: 0.35, ease: "easeInOut" }}
                className="overflow-hidden"
              >
                <div className="px-6 pb-6 border-t border-blue-100 dark:border-blue-800/20 pt-5">
                  {/* Step by step reasoning */}
                  <div className="space-y-4">
                    {steps.map((step, i) => (
                      <motion.div
                        key={i}
                        initial={{ opacity: 0, x: -15 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.1 }}
                        className="flex items-start gap-4"
                      >
                        <div className="flex-shrink-0 w-7 h-7 rounded-full bg-gradient-to-br from-blue-500 to-teal-400 flex items-center justify-center text-white text-xs font-bold">
                          {i + 1}
                        </div>
                        <p className="text-gray-700 dark:text-gray-300 text-sm leading-relaxed pt-0.5">
                          {step}
                        </p>
                      </motion.div>
                    ))}
                  </div>

                  {/* AI disclaimer note */}
                  <div className="mt-6 p-4 rounded-xl bg-violet-50 dark:bg-violet-900/10 border border-violet-100 dark:border-violet-800/20">
                    <p className="text-xs text-violet-700 dark:text-violet-400 leading-relaxed font-mono">
                      <span className="font-bold">AI Analysis Note:</span> This reasoning is
                      generated by Google Gemini AI based on the symptom patterns you provided.
                      It is designed to inform, not diagnose. Always confirm with a licensed
                      healthcare professional.
                    </p>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </motion.section>
  );
}
